# https://docs.travis-ci.com/

language: minimal

services:
  - docker

addons:
  hosts:
    - server.localhost
    - www-server.localhost
    - www.server.localhost
    - secure.server.localhost
    - www.secure.server.localhost
  apt:
    packages:
      - docker-ce

install:
  - curl -sSL https://github.com/h5bp/server-configs-test/releases/download/1.0.1/server-configs-test.tar.gz | tar -xz -C test/

before_script:
  - bash -c "./bin/build.sh test/fixtures/.htaccess test/build/htaccess_fixture.conf"
  - docker pull httpd
  - |
    docker run -d -p 80:80 -p 443:443 --name server \
      -v $TRAVIS_BUILD_DIR/test/fixtures:/usr/local/apache2/htdocs \
      -v $TRAVIS_BUILD_DIR/test/vhosts/httpd.conf:/usr/local/apache2/conf/httpd.conf \
      httpd

#      -v $TRAVIS_BUILD_DIR/test/vhosts:/usr/local/apache2/vhosts \
#      -v $TRAVIS_BUILD_DIR/test/certs:/usr/local/apache2/certs \
#      -v $TRAVIS_BUILD_DIR/h5bp:/usr/local/apache2/h5bp \
#      -v $TRAVIS_BUILD_DIR/httpd.conf:/usr/local/apache2/conf/httpd.conf \
#      -v $TRAVIS_BUILD_DIR/mime.types:/usr/local/apache2/conf/mime.types \
#      httpd

script:
  - ./test/bin/k6 run test/lib/index.js -e TESTS=basic-file-access:cache-busting:custom-errors:forbidden-files:enforce-gzip:precompressed-files-gzip:concatenation
  - bash -c "./test/build/test_userbuild.sh"

after_success: ./test/bin/k6 run test/lib/benchmark.js

after_failure:
  - docker ps -a
  - docker logs server

before_deploy: bash -c "bin/build.sh dist/.htaccess htaccess.conf"

deploy:
  - provider: releases
    api_key: $GITHUB_API_TOKEN
    file: dist/.htaccess
    skip_cleanup: true
    on:
      tags: true
  - provider: npm
    email: $NPM_API_EMAIL
    api_key: $NPM_API_TOKEN
    skip_cleanup: true
    on:
      tags: true
