# For more information about the configurations used
# in this file, please see the Travis CI documentation:
# http://docs.travis-ci.com

after_success:
  - |
      # Automatically update the content from the `dist/` directory
      $(npm bin)/commit-changes --branch "master" \
                                --commands "npm run build" \
                                --commit-message "Update the generated content [skip ci]"

before_script:
  - ./bin/setup/setup.sh

env:
  global:
    - BUILD_DIR="$TRAVIS_BUILD_DIR"
    - secure: "KdKjkn16idVwU/znf7HLztR8sq0NX7i1qWEbB7y96zdSH9NYzN2KndcjkjBfhK6qawVJ3mDVyYCr46VRalJR+AlnbwDddGKJ9+Aclk61uf6PUuLF6gHr2kwpGWpvl9zgdFKlLbRqd2lRBJw5DC3ene5qPZ2G22Ymkhdw/PTHkMY="

git:
  depth: 5

language: node_js

matrix:
  include:

    # Tests for Apache 2.2.x

    - env:
        - APACHE_VERSION="2.2.x"
      node_js: "8"
      script:
        - sudo service apache2 restart
        - npm test


    # Tests for Apache 2.4.x

    - env:
        - APACHE_VERSION="2.4.x"
      node_js: "8"
      script:
        - sudo /usr/local/apache2/bin/apachectl start
        - npm test
